Repository you-dont-need/You-Dont-Need-JavaScript, pull requests merged in 2023-10, with the labels that each got.

#331 Create retro background
  retro background
Labels: hacktober-accepted

#334 feat: Create a CSS Loader with name svg
  CSS-Loader/purnasth/index.html
  CSS-Loader/purnasth/style.css
  README.md
  images/css-loader-purna.gif
Labels: hacktober-accepted

#333 Added Responsive Footer
  Assests/Footer.png
  Login/Signin.css
  Login/Signin.html
  README.md
  Responsive Footer/Footer.css
  Responsive Footer/index.html
Labels: PR Welcome

#319 Added an Animation Box
  .gitignore
  README.md
  Square Animation/ezgif.com-video-to-gif.gif
  Square Animation/index.html
  Square Animation/style.css
  images/AnimatedBox.jpg
  images/AnimatedBox2.jpg
Labels: duplicate

#394 Arrow and different symbols using PURE CSS #388 PULL REQUEST
  Shapes/Shapes.png
  Shapes/index.html
  Shapes/style.css
Labels: hacktober-accepted, hacktoberfest
