Repository you-dont-need/You-Dont-Need-JavaScript, pull requests merged in 2024-10, with the labels that each got.

#444 Improve login page responsiveness
  Login_Page/style.css
Labels: hacktober-accepted

#453 Added Profile Cards
  Card1.html
  card1.css
  card2.css
  card2.html
Labels: hacktober-accepted

#460 Adding website fully based on HTML CSS
  README.md
  Web_Demo/Buy_a_home.webp
  Web_Demo/GatedCarousel_Desktop (1).webp
  Web_Demo/IvarHeadline-SemiBold-core.ttf
  Web_Demo/Rent_a_home.webp
  Web_Demo/Sell_a_home.webp
  Web_Demo/app-store-badge.png
  Web_Demo/app-store-badge.svg
  Web_Demo/favicon.ico
  Web_Demo/footer.png
  Web_Demo/footer.svg
  Web_Demo/google-play-badge.png
  Web_Demo/google-play-badge.svg
  Web_Demo/index.html
  Web_Demo/main-bg.webp
  Web_Demo/mem5YaGs126MiZpBA-UNirkOUuhpKKSTjw.ttf
  Web_Demo/mem8YaGs126MiZpBA-UFVZ0bf8pkAg.ttf
  Web_Demo/style.css
  Web_Demo/z-logo.png
  Web_Demo/z-logo.svg
  images/Website_demo.png
  images/Website_demo_2.png
  images/Website_demo_3.png
Labels: hacktober-accepted

#471 Added Blogpost cards
  BLOG POST CARDS/Glasscard.html
  BLOG POST CARDS/claycard.css
  BLOG POST CARDS/claycard.html
  BLOG POST CARDS/claycards.png
  BLOG POST CARDS/glasscards.png
  BLOG POST CARDS/neuo.png
  BLOG POST CARDS/neuocards.css
  BLOG POST CARDS/neuocards.html
  BLOG POST CARDS/styles.css
  README.md
  images/claycards.png
  images/glasscards.png
  images/neuo.png
Labels: hacktober-accepted

#466 Update Separate div Elements for Clock Hands index.html
  Analog-clock/index.html
Labels: hacktober-accepted

#551 Fixing the Issue with the Portfolio Website
  Portfoliowebsite/Portfolio Preview.png
  Portfoliowebsite/port.css
  Portfoliowebsite/port.html
Labels: hacktoberfest-accepted, hacktoberfest

#668 Automatic Sliding Image system using CSS
  Sliding Images and NavBar/page.html
Labels: hacktoberfest-accepted
